# Generated by Django 4.0.6 on 2022-09-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='titre',
            new_name='projet',
        ),
        migrations.AddField(
            model_name='commande',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='tel',
            field=models.CharField(default='------------', max_length=20),
        ),
    ]
