# Generated by Django 4.0.6 on 2022-09-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_titre_commande_projet_commande_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='service',
        ),
    ]
