# Generated by Django 4.0.6 on 2022-09-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='ibavdigital', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='ibavdigital', max_length=200),
        ),
        migrations.AddField(
            model_name='terms',
            name='title',
            field=models.CharField(default='ibavdigital', max_length=200),
        ),
    ]
