# Generated by Django 4.0.6 on 2022-09-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_portfolio_title_service_title_terms_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='ibav'),
        ),
    ]
