# Generated by Django 4.0.6 on 2022-09-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacteur',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prospect',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
    ]
