# Generated by Django 4.0.6 on 2022-09-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contacteur_telephone_prospect_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacteur',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='name',
            new_name='username',
        ),
    ]
