# Generated by Django 4.0.6 on 2022-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_name_contacteur_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacteur',
            name='telephone',
            field=models.CharField(default='-------------', max_length=20),
        ),
    ]
