# Generated by Django 4.0.6 on 2022-09-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_contacteur_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='telephone',
            field=models.CharField(default='-------------', max_length=20),
        ),
    ]
