# Generated by Django 4.0.6 on 2022-09-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_content_alter_section_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='ibavdigital', max_length=200),
        ),
        migrations.DeleteModel(
            name='Section_post',
        ),
    ]
