# Generated by Django 4.0.6 on 2022-09-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_title_delete_section_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_desc',
            field=models.CharField(default="Aujourd'hui, posséder un site web est indisssociable pour une entreprise car l'image que vous projetez sur le web est déterminante. C'est pourquoi, il est essentiel de disposer d'un site Internet attractif et fonctionnel", max_length=500),
        ),
    ]
