# Generated by Django 4.0.6 on 2022-09-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_meta_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
